# Tools configuration

[tools]
erlang = "29.0.6"
elixir = "1.20.4-otp-29"

[tasks.format]
description = "Format the codebase"
run = "mix format"

[tasks.test]
description = "Run the test suite"
run = "mix test"

[tasks.lint]
description = "Format and lint the codebase"
depends = ["format"]
run = "mix credo --strict"

[tasks.analyze]
description = "Format, lint, and analyze the codebase"
depends = ["lint"]
run = "mix dialyzer"

[tasks.fix]
description = "Format, lint, analyze, and test the codebase"
depends = ["analyze"]
run = "mix test"
